// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wAefUEUxESxVlLwjhXhFcBxQUGQmfS8',
    appId: '1:815908073019:android:b8d9c5faa2fa103417b61e',
    messagingSenderId: '815908073019',
    projectId: 'cse1-teaml1',
    storageBucket: 'cse1-teaml1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk2Sg-HJj11jiA2GtJoRKt9PirSk-POZk',
    appId: '1:815908073019:ios:72b1d587aca7d34317b61e',
    messagingSenderId: '815908073019',
    projectId: 'cse1-teaml1',
    storageBucket: 'cse1-teaml1.firebasestorage.app',
    androidClientId: '815908073019-fsgg080nrc8e8tatfdr3begg143jpag8.apps.googleusercontent.com',
    iosClientId: '815908073019-bmnhgb056qosgb4q6co7ccnk9gh0qd80.apps.googleusercontent.com',
    iosBundleId: 'com.example.univentsApp',
  );

}