// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpjbNaoi4DWduztHetPAo8OlWBxN1mMWk',
    appId: '1:815908073019:web:1086dbc623943a1117b61e',
    messagingSenderId: '815908073019',
    projectId: 'cse1-teaml1',
    authDomain: 'cse1-teaml1.firebaseapp.com',
    storageBucket: 'cse1-teaml1.firebasestorage.app',
    measurementId: 'G-1RSC1SV823',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0wAefUEUxESxVlLwjhXhFcBxQUGQmfS8',
    appId: '1:815908073019:android:40a550c810b175fb17b61e',
    messagingSenderId: '815908073019',
    projectId: 'cse1-teaml1',
    storageBucket: 'cse1-teaml1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk2Sg-HJj11jiA2GtJoRKt9PirSk-POZk',
    appId: '1:815908073019:ios:34aec8d2f5ca3ca017b61e',
    messagingSenderId: '815908073019',
    projectId: 'cse1-teaml1',
    storageBucket: 'cse1-teaml1.firebasestorage.app',
    iosClientId: '815908073019-rm6pb65ndprq1rtm960hl5nf8ak41sg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.finals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk2Sg-HJj11jiA2GtJoRKt9PirSk-POZk',
    appId: '1:815908073019:ios:34aec8d2f5ca3ca017b61e',
    messagingSenderId: '815908073019',
    projectId: 'cse1-teaml1',
    storageBucket: 'cse1-teaml1.firebasestorage.app',
    iosClientId: '815908073019-rm6pb65ndprq1rtm960hl5nf8ak41sg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.finals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpjbNaoi4DWduztHetPAo8OlWBxN1mMWk',
    appId: '1:815908073019:web:4786e6722d3d5ba117b61e',
    messagingSenderId: '815908073019',
    projectId: 'cse1-teaml1',
    authDomain: 'cse1-teaml1.firebaseapp.com',
    storageBucket: 'cse1-teaml1.firebasestorage.app',
    measurementId: 'G-Z1FDZ7X4Y8',
  );
}
